### ISSUE TITLE
elo

### ISSUE THREAD

**Issue by xnerdian** [xVacuum/qEssentials#1]
elo

**Comment by TheMolkaPL** [comment]
jakie elo?
to są podstawowe komendy nie rankingi :bulb:

**Comment by xnerdian** [comment]
acha

**Comment by Meehoweq** [comment]
TheMolka, skisłem XD

**Comment by TheMolkaPL** [comment]
?

**Comment by xnerdian** [comment]
TheMolkaPL hah ja też skisłem haha dobre.  Elo = ranking, teraz zaczailem

**Comment by TheMolkaPL** [comment]
Ja nie wiem o co Wam chodzi.... Napisał "elo" czyli chodzi o ranking... nie ogarniam...
